In [2]:
import numpy as np
np.__version__

'1.18.1'

In [3]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [11]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.random.random((3,3))

array([[0.33783784, 0.07878157, 0.75144789],
       [0.35405191, 0.76257083, 0.08569028],
       [0.84380687, 0.82774888, 0.03496205]])

In [17]:
np.random.normal(0,1,(4,4))

array([[ 0.4639865 ,  0.90489156, -0.14615013,  0.94046981],
       [-0.51629793, -2.36475361,  0.23859531,  1.01269483],
       [ 0.15776364, -0.95714601, -0.90233205, -0.42193923],
       [ 0.30154429, -1.3269787 ,  0.41226333,  0.41015739]])

In [18]:
np.random.randint(0,100,(5,5))

array([[29, 92, 14, 72, 94],
       [69, 49, 86, 30, 23],
       [63,  9, 47, 44, 98],
       [81, 17, 89, 90, 50],
       [59, 39, 13, 86,  6]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Attributes of arrays

Determining the size, shape, memory consumption, and data types of arrays

In [20]:
np.random.seed(0)
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [24]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)
print("x3 itemsize : ", x3.itemsize, "bytes")
print("x3 nbytes: ", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64
x3 itemsize :  8 bytes
x3 nbytes:  480 bytes


#### Indexing of arrays

Gettign and setting the value of individual array elements

In [28]:
print(x1)
print(x1[4])
print(x1[-2])

[5 0 3 3 7 9]
7
7


In [37]:
print(x2)
print(x2[1,1])
print(x2[2,0])
print(x2[0,-3])

x2[0,0] = 12 # to modify value - will truncate new value type to that of the array type

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
6
1
5


#### Slicing of arrays

Getting and setting smaller subarrays within a larger array

In [31]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
print(x[:5])
print(x[5:])
print(x[4:7])

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]


In [35]:
print(x[::2])
print(x[1::2])
print(x[::-1])
print(x[5::-2])

[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [38]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [40]:
print(x2[:3, ::2])
print(x2[:2,:3])
print(x2[::-1,::-1])

[[12  2]
 [ 7  8]
 [ 1  7]]
[[12  5  2]
 [ 7  6  8]]
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


In [45]:
# accessing array rows and columns
print(x2)
print(x2[:,0])
print(x2[0,:])
print(x2[0])

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[12  7  1]
[12  5  2  4]
[12  5  2  4]


In [46]:
x2_sub_copy = x2[:2,:2].copy() # want to copy the array so that if we modify this subarray, the original array is not touched
x2_sub_copy[0,0] = 42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#### Reshaping of arrays

Changing the shape of a given array

In [48]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
x=np.array([1,2,3])
x


array([1, 2, 3])

In [52]:
x.reshape((1,3))

array([[1, 2, 3]])

In [53]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [54]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [56]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

#### Joining and splitting of arrays

Combining multiple arrays into one, and splitting one array into many

In [59]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [61]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [62]:
grid = np.array([[1,2,3],
                 [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [68]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [70]:
y = np.array([[99],
              [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [71]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [72]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [76]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
