In [3]:
import pandas as pd
import numpy as np

### The Pandas Series Object

In [4]:
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64


In [8]:
data = pd.Series([0.25,0.5,0.75,1.0],
                 index=["a","b","c","d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
data["b"]

0.5

In [10]:
population_dict = {"California": 38332521,
                   "Texas": 26448193,
                   "New York": 19651127,
                   "Florida": 19552860,
                   "Illinois": 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [11]:
print(population["California"])
print(population["California":"Illinois"])

38332521
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [12]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [13]:
pd.Series(5, index = [100,200,300])

100    5
200    5
300    5
dtype: int64

### The Pandas DataFrame Object

In [14]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [15]:
states = pd.DataFrame({"population": population,
                       "area": area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [16]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [17]:
states.columns

Index(['population', 'area'], dtype='object')

In [18]:
pd.DataFrame(np.random.rand(3,2),
             columns = ["foo","bar"],
             index = ["a","b","c"])

foo       bar
a  0.577652  0.995356
b  0.738752  0.831719
c  0.048478  0.057479

### The Pandas Index Object

In [19]:
indA = pd.Index([1, 3, 5, 7, 9]) 
indB = pd.Index([2, 3, 5, 7, 11])

In [20]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [21]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [22]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

### Data Indexing and Selection

#### Data Selection in Series

In [23]:
data = pd.Series([0.25,0.5,0.75,1.0],
                 index=["a","b","c","d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [24]:
data["b"]

0.5

In [25]:
"a" in data

True

In [26]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [27]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [28]:
data["e"] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [29]:
data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [30]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [31]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [32]:
data[["a","e"]]

a    0.25
e    1.25
dtype: float64

`loc` attribute allows indexing and slicing that always references the explicit index:

In [41]:
data = pd.Series(["a","b","c"], index = [1,3,5])
data


1    a
3    b
5    c
dtype: object

In [42]:
data.loc[1]

'a'

In [37]:
data.loc[1:3]

1    a
3    b
dtype: object

In [38]:
data.iloc[1]

'b'

In [39]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [40]:
data.iloc[1:2]

3    b
dtype: object

### Data Selection in DataFrame

In [43]:
area = pd.Series({'California': 423967, 'Texas': 695662, 
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [44]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [45]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [46]:
data["density"] = data["pop"] / data["area"]
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [47]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [49]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [50]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [51]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [52]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [53]:
data.loc[:"Illinois",:"pop"]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [54]:
data.loc[data.density > 100, ["pop","density"]]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [55]:
data.iloc[0,2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Operating on Data in Pandas

In [57]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [58]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                  columns = ["A","B","C","D"])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [59]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [60]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [61]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 
                        'New York': 19651127}, name='population')

In [62]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [63]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [64]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [65]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [66]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [67]:
A+B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [69]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [70]:
A = rng.randint(10, size=(3,4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [71]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [72]:
df = pd.DataFrame(A, columns=list("QRST"))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [75]:
df.subtract(df["R"], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [76]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int64

### Missing Data in Pandas

In [77]:
vals1 = np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [78]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [79]:
vals2 = np.array([1,np.nan,3,4])
vals2

array([ 1., nan,  3.,  4.])

In [80]:
vals2.sum()

nan

In [81]:
np.nansum(vals2) , np.nanmin(vals2) , np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [82]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

### Operating on Null Values

In [83]:
data = pd.Series([1, np.nan, "hello", None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [84]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [85]:
data.dropna()

0        1
2    hello
dtype: object

In [86]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [87]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [88]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [89]:
df.dropna(axis="columns")

2
0  2
1  5
2  6

In [90]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [91]:
df.dropna(axis="columns",how="all")

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [92]:
df.dropna(axis = "rows", thresh = 3)

0    1  2   3
1  2.0  3.0  5 NaN

In [93]:
data = pd.Series([1,np.nan,2,None,3], index = list("abcde"))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [94]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [95]:
# forward fill
data.fillna(method="ffill")

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [96]:
# back fill
data.fillna(method="bfill")

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [97]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [100]:
df.fillna(method="ffill",axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

#### Multiindex

In [102]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
index = pd.MultiIndex.from_tuples(index)
print(index)
pop = pop.reindex(index)
print(pop)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


In [103]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [104]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [105]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [106]:
pop_df = pd.DataFrame({"total": pop,
                       "under18":[9267089,9284094,
                                  4687374,4318033,
                                  5906301,6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [109]:
f_u18 = pop_df["under18"] / pop_df["total"]
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [110]:
pop.index.names = ["state","year"]
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [111]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])
# mock some data
data = np.round(np.random.randn(4, 6), 1) 
data[:, ::2] *= 10
data += 37
# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns) 
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      42.0  37.5  19.0  37.9  31.0  39.0
     2      29.0  34.7  30.0  37.9  39.0  36.7
2014 1      45.0  35.8  42.0  34.2  40.0  37.4
     2      11.0  37.3  32.0  34.6  49.0  37.6

In [119]:
health_data["Guido"]

type          HR  Temp
year visit            
2013 1      19.0  37.9
     2      30.0  37.9
2014 1      42.0  34.2
     2      32.0  34.6

In [113]:
pop["California",2000]

33871648

In [114]:
pop["California"]

year
2000    33871648
2010    37253956
dtype: int64

In [115]:
pop.loc["California":"New York"]

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [116]:
pop[:,2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [120]:
pop[pop>22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [121]:
pop[["California","Texas"]]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [123]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      42.0  37.5  19.0  37.9  31.0  39.0
     2      29.0  34.7  30.0  37.9  39.0  36.7
2014 1      45.0  35.8  42.0  34.2  40.0  37.4
     2      11.0  37.3  32.0  34.6  49.0  37.6

In [125]:
health_data["Guido","HR"]

year  visit
2013  1        19.0
      2        30.0
2014  1        42.0
      2        32.0
Name: (Guido, HR), dtype: float64

In [126]:
health_data.iloc[:2,:2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      42.0  37.5
     2      29.0  34.7

In [127]:
health_data.loc[:,("Bob","HR")]

year  visit
2013  1        42.0
      2        29.0
2014  1        45.0
      2        11.0
Name: (Bob, HR), dtype: float64

In [128]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]]) 
data = pd.Series(np.random.rand(6), index=index) 
data.index.names = ['char', 'int']
data

char  int
a     1      0.910869
      2      0.884585
c     1      0.502449
      2      0.263678
b     1      0.659700
      2      0.452053
dtype: float64

In [129]:
data = data.sort_index() 
data

char  int
a     1      0.910869
      2      0.884585
b     1      0.659700
      2      0.452053
c     1      0.502449
      2      0.263678
dtype: float64

In [130]:
data["a":"b"]

char  int
a     1      0.910869
      2      0.884585
b     1      0.659700
      2      0.452053
dtype: float64

In [131]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [132]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [133]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [135]:
pop_flat = pop.reset_index(name = "population")
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [136]:
pop_flat.set_index(["state","year"])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [137]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      42.0  37.5  19.0  37.9  31.0  39.0
     2      29.0  34.7  30.0  37.9  39.0  36.7
2014 1      45.0  35.8  42.0  34.2  40.0  37.4
     2      11.0  37.3  32.0  34.6  49.0  37.6

In [138]:
data_mean = health_data.mean(level="year")
data_mean

subject   Bob        Guido         Sue       
type       HR   Temp    HR  Temp    HR   Temp
year                                         
2013     35.5  36.10  24.5  37.9  35.0  37.85
2014     28.0  36.55  37.0  34.4  44.5  37.50

In [139]:
data_mean.mean(axis=1, level="type")

type         HR       Temp
year                      
2013  31.666667  37.283333
2014  36.500000  36.150000

###  Combining Datasets: Concat and Append

In [140]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data,ind)

make_df("ABC", range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [142]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
x = [[1,2],
     [3,4]]
np.concatenate([x,x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [144]:
ser1 = pd.Series(["A","B","C"], index=[1,2,3])
ser2 = pd.Series(["D","E","F"], index=[4,5,6])
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [146]:
df1 = make_df("AB", [1,2])
df2 = make_df("AB", [3,4])
print(df1); print(df2); print(pd.concat([df1,df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [148]:
df3 = make_df("AB", [0,1])
df4 = make_df("CD", [0,1])
print(df3); print(df4); print(pd.concat([df3,df4], axis=1))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [151]:
x = make_df("AB", [0,1])
y = make_df("AB", [2,3])
y.index = x.index
print(x); print(y); print(pd.concat([x,y]))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [152]:
print(x); print(y); print(pd.concat([x,y], ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [155]:
df5 = make_df("ABC",[1,2])
df6 = make_df("BCD",[3,4])
print(df5); print(df6); print(pd.concat([df5,df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


In [156]:
print(df5);print(df6);print(pd.concat([df5,df6], join="inner"))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [157]:
print(df1);print(df2);print(df1.append(df2))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


### Merge and Join



In [158]:
df1 = pd.DataFrame({"employee": ["Bob","Jake","Lisa","Sue"],
                    "group": ["Accounting","Engineering","Engineering","HR"]})
df2 = pd.DataFrame({"employee":["Lisa","Bob","Jake","Sue"],
                    "hire_date":[2004,2008,2012,2014]})
print(df1);print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [159]:
df3 = pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [160]:
df4 = pd.DataFrame({"group":["Accounting","Engineering","HR"],
                    "supervisor":["Carly","Guido","Steve"]})
print(df3); print(df4); print(pd.merge(df3,df4))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


In [163]:
df5 = pd.DataFrame({"group":["Accounting","Accounting","Engineering","Engineering","HR","HR"],
                    "skills":["math","spreadsheets","coding","linux","spreadsheets","organization"]})
print(df1); print(df5); print(pd.merge(df1,df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization


In [164]:
print(df1); print(df2); print(pd.merge(df1,df2, on="employee"))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [165]:
df3 = pd.DataFrame({"name":["Bob","Jake","Lisa","Sue"],
                    "salary":[70000,80000,120000,90000]})
print(df1);print(df3);
print(pd.merge(df1,df3,left_on="employee",right_on="name"))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000


In [168]:
pd.merge(df1,df3,left_on="employee",right_on="name").drop("name",axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [170]:
df6 = pd.DataFrame({"name":["Peter","Paul","Mary"],
                    "food":["fish","beans","bread"]},
                   columns=["name","food"])
df7 = pd.DataFrame({"name":["Mary","Joseph"],
                    "drink":["wine","beer"]},
                   columns=["name","drink"])
print(df6); print(df7); print(pd.merge(df6,df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
   name   food drink
0  Mary  bread  wine


In [171]:
pd.merge(df6,df7,how="outer")

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [172]:
pd.merge(df6,df7,how="left")

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

#### Example: US States Data

In [182]:
pop = pd.read_csv("../_data/state-population.csv")
areas = pd.read_csv("../_data/state-areas.csv")
abbrevs = pd.read_csv("../_data/state-abbrevs.csv")
print(pop.head()); print(area.head()); print(abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA


In [176]:
merged = pd.merge(pop, abbrevs, how="outer",
                   left_on="state/region", right_on="abbreviation")
merged = merged.drop("abbreviation", axis=1)
merged.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [177]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [178]:
merged[merged["population"].isnull()].head()

state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN

In [179]:
merged.loc[merged["state"].isnull(),"state/region"].unique()

array(['PR', 'USA'], dtype=object)

In [180]:
merged.loc[merged["state/region"] == "PR", "state"] = "Puerto Rico"
merged.loc[merged["state/region"] == "USA", "state"] = "United States"
merged.isnull().any()


state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [183]:
final = pd.merge(merged, areas, on="state",how="left")
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [184]:
final.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [185]:
final["state"][final["area (sq. mi)"].isnull()].unique()

array(['United States'], dtype=object)

In [186]:
final.dropna(inplace=True)
print(final.head()); print(final.isnull().any())

  state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0
state/region     False
ages             False
year             False
population       False
state            False
area (sq. mi)    False
dtype: bool


In [193]:
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [194]:
data2010.set_index(['state'], inplace=True)
density = data2010["population"] / data2010["area (sq. mi)"]
density.sort_values(ascending = False, inplace = True)
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64

In [195]:
density.tail()

state
South Dakota    10.583512
North Dakota     9.537565
Montana          6.736171
Wyoming          5.768079
Alaska           1.087509
dtype: float64

### Aggregation and Grouping