In [3]:
import pandas as pd
import numpy as np

### The Pandas Series Object

In [4]:
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64


In [8]:
data = pd.Series([0.25,0.5,0.75,1.0],
                 index=["a","b","c","d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
data["b"]

0.5

In [10]:
population_dict = {"California": 38332521,
                   "Texas": 26448193,
                   "New York": 19651127,
                   "Florida": 19552860,
                   "Illinois": 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [11]:
print(population["California"])
print(population["California":"Illinois"])

38332521
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [12]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [13]:
pd.Series(5, index = [100,200,300])

100    5
200    5
300    5
dtype: int64

### The Pandas DataFrame Object

In [14]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [15]:
states = pd.DataFrame({"population": population,
                       "area": area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [16]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [17]:
states.columns

Index(['population', 'area'], dtype='object')

In [18]:
pd.DataFrame(np.random.rand(3,2),
             columns = ["foo","bar"],
             index = ["a","b","c"])

foo       bar
a  0.577652  0.995356
b  0.738752  0.831719
c  0.048478  0.057479

### The Pandas Index Object

In [19]:
indA = pd.Index([1, 3, 5, 7, 9]) 
indB = pd.Index([2, 3, 5, 7, 11])

In [20]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [21]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [22]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

### Data Indexing and Selection

#### Data Selection in Series

In [23]:
data = pd.Series([0.25,0.5,0.75,1.0],
                 index=["a","b","c","d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [24]:
data["b"]

0.5

In [25]:
"a" in data

True

In [26]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [27]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [28]:
data["e"] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [29]:
data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [30]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [31]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [32]:
data[["a","e"]]

a    0.25
e    1.25
dtype: float64

`loc` attribute allows indexing and slicing that always references the explicit index:

In [41]:
data = pd.Series(["a","b","c"], index = [1,3,5])
data


1    a
3    b
5    c
dtype: object

In [42]:
data.loc[1]

'a'

In [37]:
data.loc[1:3]

1    a
3    b
dtype: object

In [38]:
data.iloc[1]

'b'

In [39]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [40]:
data.iloc[1:2]

3    b
dtype: object

### Data Selection in DataFrame

In [43]:
area = pd.Series({'California': 423967, 'Texas': 695662, 
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [44]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [45]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [46]:
data["density"] = data["pop"] / data["area"]
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [47]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [49]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [50]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [51]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [52]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [53]:
data.loc[:"Illinois",:"pop"]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [54]:
data.loc[data.density > 100, ["pop","density"]]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [55]:
data.iloc[0,2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Operating on Data in Pandas

In [57]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [58]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                  columns = ["A","B","C","D"])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [59]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [60]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [61]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 
                        'New York': 19651127}, name='population')

In [62]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [63]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [64]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [65]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [66]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [67]:
A+B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [69]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [70]:
A = rng.randint(10, size=(3,4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [71]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [72]:
df = pd.DataFrame(A, columns=list("QRST"))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [75]:
df.subtract(df["R"], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [76]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int64

### Missing Data in Pandas

In [77]:
vals1 = np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [78]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [79]:
vals2 = np.array([1,np.nan,3,4])
vals2

array([ 1., nan,  3.,  4.])

In [80]:
vals2.sum()

nan

In [81]:
np.nansum(vals2) , np.nanmin(vals2) , np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [82]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

### Operating on Null Values

In [83]:
data = pd.Series([1, np.nan, "hello", None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [84]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [85]:
data.dropna()

0        1
2    hello
dtype: object

In [86]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [87]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [88]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [89]:
df.dropna(axis="columns")

2
0  2
1  5
2  6

In [90]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [91]:
df.dropna(axis="columns",how="all")

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [92]:
df.dropna(axis = "rows", thresh = 3)

0    1  2   3
1  2.0  3.0  5 NaN

In [93]:
data = pd.Series([1,np.nan,2,None,3], index = list("abcde"))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [94]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [95]:
# forward fill
data.fillna(method="ffill")

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [96]:
# back fill
data.fillna(method="bfill")

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64